[app]
device_name=%(DEVICE_NAME)s
cronitor_monitor_key=%(CRONITOR_MONITOR_KEY)s
paging_enabled=%(PAGING_ENABLED)s

[alert_thresholds]
minimum_bms_count = %(MINIMUM_BMS_COUNT)s

[creds]
cronitor=Cronitor/password
sentry_dsn=Sentry/__APP_NAME__/dsn

[metrics]
network_port=9401
debug_csv=%(METRICS_DEBUG_CSV)s

[mqtt]
server_address = %(MQTT_SERVER_ADDRESS)s
topic_prefix = %(MQTT_TOPIC_PREFIX)s
switch_device_csv = %(MQTT_SWITCH_DEVICE_CSV)s

[bms]
logging_enabled = %(BMS_LOGGING_ENABLED)s
serial_port = %(BMS_SERIAL_PORT)s


[inverter]
logging_enabled = %(INVERTER_LOGGING_ENABLED)s
logger_address = %(INVERTER_LOGGER_ADDRESS)s
logger_port = %(INVERTER_LOGGER_PORT)s
logger_sn = %(INVERTER_LOGGER_SN)s
logger_sample_interval_seconds = %(INVERTER_LOGGER_SAMPLE_INTERVAL_SECS)s

[weather]
coord_lat_lon = %(WEATHER_COORD)s

[telegram]
enabled_users_csv = %(TELEGRAM_ENABLED_USERS_CSV)s
history_hours = %(TELEGRAM_HISTORY_HOURS)s
help_url = %(TELEGRAM_HELP_URL)s
